backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featuredimage", widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "events"
    label: "Events"
    folder: "src/pages/events"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event-single"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Event Date", name: "date", widget: "datetime", required: true, time_format: false}
      - {label: "Start Time", name: "start_time", widget: "datetime", required: true, picker_utc: true, date_format: false, time_format: true}
      - {label: "End Time", name: "end_time", widget: "datetime", required: true, picker_utc: true, date_format: false, time_format: true}
      - {label: "Meta Description", name: "description", widget: "text", hint: "Meta descriptions are useful for SEO. This text will NOT show on page. Use Body below for page copy."}
      - {label: "Featured Event", name: "featuredevent", widget: "boolean", required: false}
      - {label: "Featured Image", name: "featuredimage", widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Recording link", name: "recording", widget: "string", required: false}
      - label: "Address"
        name: "address"
        hint: "Don't enter this information if event is online"
        widget: "object"
        collapsed: true
        fields:
        - {label: "Name", name: "location_name", widget: "string", required: false}
        - {label: "Street Address", name: "street", widget: "string", required: false}
        - {label: "City", name: "city", widget: "string", required: false}
        - {label: "Postal Code", name: "post-code", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:

      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Body, name: body, widget: markdown}

      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: "Blurb", name: "blurb", widget: "markdown"}
              - {label: Photo, name: photo, widget: image}

      - file: "src/pages/events/events-landing.md"
        label: "Events Test"
        name: "test"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "landing-page"}
          - {label: Image, name: image, widget: image}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/resources.md"
        label: "Resources"
        name: "resources"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "landing-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/donate.md"
        label: "Donate"
        name: "donate"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "donate-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: Tiers
            name: tiers
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Price, name: price, widget: number}
              - {label: Description, name: description, widget: markdown}
